let playlists = [
  { id: "182", playlist: ["tbd"] },
  { id: "181", playlist: ["tbd"] },
  { id: "180", playlist: ["tbd"] },
  { id: "179", playlist: ["tbd"] },
  { id: "178", playlist: ["tbd"] },
  { id: "177", playlist: ["tbd"] },
  { id: "176", playlist: ["tbd"] },
  { id: "175", playlist: ["tbd"] },
  { id: "174", playlist: ["tbd"] },
  { id: "173", playlist: ["tbd"] },
  { id: "172", playlist: ["tbd"] },
  { id: "171", playlist: ["tbd"] },
  {
    id: "170",
    playlist: [
      "Raiya Sees",
      "Untitled 1",
      "Puppies",
      "Bird's Eye",
      "The Tuesday Headache",
      "Toothbrush Fight",
      "Gold Guitar Theory",
      "Swashbuckling Squids",
      "Reload",
      "High School",
    ],
  },
  {
    id: "169",
    playlist: [
      "Simplistic Glove",
      "Olivia's Pots",
      "Untitled 3",
      "K\\u014dkako",
      "Mountains of the M",
      "Top",
      "Blue Orange",
      "Hydroplane",
      "Ananas comosus",
      "Harmony Vase",
    ],
  },
  {
    id: "168",
    playlist: [
      "Greypeak Range",
      "Fuzzy Fuzzbuzz",
      "A9",
      "Self-absorbed Husbands",
      "Duke's Revenge",
      "Untitled 2",
      "The Turning Machine",
      "Moonstrike's Lament",
      "Desk Crack",
      "William",
    ],
  },
  {
    id: "167",
    playlist: [
      "Wave to the Wind",
      "Moonbeams",
      "Patrick Swayze",
      "Lockdown",
      "Sunbird Stream",
      "Car Fold",
      "Spiron Festival",
      "Krambambuli",
      "Kiwi Kea",
      "Needle",
      "Cranberry Crystals",
    ],
  },
  {
    id: "166",
    playlist: [
      "Redwoods",
      "Make It Relevant ",
      "12 or 66",
      "Dragonfire",
      "Eyes Floating in Cups",
      "Deer Crash",
      "The Wax Post",
      "Blended Together",
      "Ticket",
      "Suggested Chicken",
      "Reload",
    ],
  },
  {
    id: "165",
    playlist: [
      "Of Course",
      "High School",
      "Davy Gravy",
      "Sure",
      "Spiraling Excitement",
      "And Now the Good News",
      "Hydroplane",
      "Ku-Tut",
      "Biker",
      "Midst",
      "McDonald\\u2019s Theory",
      "Lavender",
    ],
  },
  {
    id: "164",
    playlist: [
      "Hospital Society",
      "Shh I'm Thinking",
      "Raiya Sees",
      "Current Lamp",
      "Stinky Uncle Steve",
      "Petite Pete",
      "Birthday Crook",
      "Degas & Shoal",
      "Self-absorbed Husbands",
      "Duke's Journey",
      "Blue Orange",
      "The Big Green Hill",
    ],
  },
  {
    id: "163",
    playlist: [
      "Doge Meme",
      "Untitled 1",
      "William",
      "Celsius",
      "Our 27th Song",
      "Haleakal\\u0101",
      "Apologies Owed",
      "Opalescence ",
      "The Wave",
      "The First Show",
      "Ananas comosus",
      "Lockdown",
    ],
  },
  {
    id: "162",
    playlist: [
      "Rocketships",
      "Kofi",
      "Krambambuli",
      "Spider",
      "Bird's Eye",
      "F-12",
      "On the Low Rung",
      "Moonstrike's Lament",
      "Explosions",
      "NNW",
      "K\\u014dkako",
      "Reload",
    ],
  },
  {
    id: "161",
    playlist: [
      "Moana",
      "Ugly Baby",
      "Mountains of the M",
      "Smart Flower",
      "Puppies",
      "Moonbeams",
      "Cochemeleon",
      "You First",
      "Greypeak Range",
      "Hydroplane",
      "Ticket",
    ],
  },
  {
    id: "160",
    playlist: [
      "Grey Clouds",
      "Gold Guitar Theory",
      "The Wax Post",
      "Duke's Revenge",
      "Top",
      "Four Turtles",
      "Blue Orange",
      "Waiting for Fred",
      "Go!",
      "Patrick Swayze",
      "Of Course",
    ],
  },
  {
    id: "159",
    playlist: [
      "High School",
      "Lockdown",
      "Simplistic Glove",
      "Self-absorbed Husbands",
      "Swashbuckling Squids",
      "Spiron Festival",
      "Tiger mountain",
      "Eyes Floating in Cups",
      "Desk Crack",
      "Late & Stained",
    ],
  },
  {
    id: "158",
    playlist: [
      "Olivia's Pots",
      "William",
      "Mock Orange Blossom",
      "Reload",
      "The Tuesday Headache",
      "Make It Relevant ",
      "Untitled 2",
      "Biker",
      "Raiya Sees",
      "Sunbird Stream",
    ],
  },
  {
    id: "157",
    playlist: [
      "Hydroplane",
      "Cranberry Crystals",
      "Toothbrush Fight",
      "Harmony Vase",
      "Roadlife",
      "A9",
      "Untitled 1",
      "Midst",
      "Birthday Crook",
      "Redwoods",
      "Krambambuli",
    ],
  },
  {
    id: "156",
    playlist: [
      "Untitled 3",
      "Go!",
      "Davy Gravy",
      "Fuzzy Fuzzbuzz",
      "Petite Pete",
      "Suggested Chicken",
      "Moonbeams",
      "Ananas comosus",
      "Car Fold",
      "Explosions",
    ],
  },
  {
    id: "155",
    playlist: [
      "Lockdown",
      "Stinky Uncle Steve",
      "Sure",
      "Blue Orange",
      "Deer Crash",
      "Kiwi Kea",
      "Our 27th Song",
      "The Turning Machine",
      "Ticket",
      "Moonstrike's Lament",
    ],
  },
  {
    id: "154",
    playlist: [
      "Celsius",
      "K\\u014dkako",
      "Self-absorbed Husbands",
      "William",
      "12 or 66",
      "Lavender",
      "Mountains of the M",
      "Of Course",
      "The Big Green Hill",
      "Wave to the Wind",
    ],
  },
  {
    id: "153",
    playlist: [
      "And Now the Good News",
      "Bird's Eye",
      "Shh I'm Thinking",
      "Greypeak Range",
      "Dragonfire",
      "Hydroplane",
      "Reload",
      "The First Show",
      "Patrick Swayze",
      "High School",
    ],
  },
  {
    id: "152",
    playlist: [
      "Puppies",
      "Petite Pete",
      "Biker",
      "Duke's Revenge",
      "Spider",
      "McDonald\\u2019s Theory",
      "Hospital Society",
      "Haleakal\\u0101",
      "Spiron Festival",
      "Birthday Crook",
    ],
  },
  {
    id: "151",
    playlist: [
      "Opalescence ",
      "Moonbeams",
      "F-12",
      "Krambambuli",
      "Eyes Floating in Cups",
      "Needle",
      "Smart Flower",
      "Lockdown",
      "Ku-Tut",
      "Raiya Sees",
      "The Wax Post",
      "Blended Together",
      "Current Lamp",
    ],
  },
  {
    id: "150",
    playlist: [
      "Untitled 1",
      "Duke's Journey",
      "Gold Guitar Theory",
      "Simplistic Glove",
      "Ananas comosus",
      "Ugly Baby",
      "Apologies Owed",
      "Sunbird Stream",
      "Ticket",
      "Self-absorbed Husbands",
      "Spiraling Excitement",
      "Rocketships",
    ],
  },
  {
    id: "149",
    playlist: [
      "Blue Orange",
      "On the Low Rung",
      "Make It Relevant ",
      "Doge Meme",
      "And Now the Good News",
      "Go!",
      "12 or 66",
      "Four Turtles",
      "Desk Crack",
      "Moana",
      "Redwoods",
      "Degas & Shoal",
    ],
  },
  {
    id: "148",
    playlist: [
      "The Wave",
      "Waiting for Fred",
      "Olivia's Pots",
      "Our 27th Song",
      "Late & Stained",
      "Cochemeleon",
      "Reload",
      "Of Course",
      "Suggested Chicken",
      "Kofi",
      "McDonald\\u2019s Theory",
      "A9",
    ],
  },
  {
    id: "147",
    playlist: [
      "Lockdown",
      "Explosions",
      "Hydroplane",
      "NNW",
      "William",
      "Swashbuckling Squids",
      "Top",
      "You First",
      "Puppies",
      "Midst",
      "Moonstrike's Lament",
      "Untitled 2",
    ],
  },
  {
    id: "146",
    playlist: [
      "Tiger mountain",
      "Grey Clouds",
      "High School",
      "Davy Gravy",
      "Cranberry Crystals",
      "Birthday Crook",
      "Mountains of the M",
      "Ugly Baby",
      "Moonbeams",
      "The Tuesday Headache",
      "Sure",
    ],
  },
  {
    id: "145",
    playlist: [
      "Petite Pete",
      "Mock Orange Blossom",
      "Stinky Uncle Steve",
      "Greypeak Range",
      "Fuzzy Fuzzbuzz",
      "Harmony Vase",
      "And Now the Good News",
      "Self-absorbed Husbands",
      "Krambambuli",
      "K\\u014dkako",
    ],
  },
  {
    id: "144",
    playlist: [
      "Blue Orange",
      "Car Fold",
      "Spiron Festival",
      "Deer Crash",
      "Ticket",
      "Celsius",
      "Toothbrush Fight",
      "Patrick Swayze",
      "Reload",
      "Raiya Sees",
    ],
  },
  {
    id: "143",
    playlist: [
      "Roadlife",
      "Late & Stained",
      "Kiwi Kea",
      "The Wax Post",
      "Ananas comosus",
      "The Big Green Hill",
      "Untitled 3",
      "12 or 66",
      "Duke's Revenge",
      "You First",
      "Bird's Eye",
    ],
  },
  {
    id: "142",
    playlist: [
      "The Turning Machine",
      "Untitled 1",
      "Ugly Baby",
      "Lavender",
      "Eyes Floating in Cups",
      "McDonald\\u2019s Theory",
      "The First Show",
      "Puppies",
      "Biker",
      "Go!",
    ],
  },
  {
    id: "141",
    playlist: [
      "Spider",
      "High School",
      "F-12",
      "Sunbird Stream",
      "Make It Relevant ",
      "Wave to the Wind",
      "Shh I'm Thinking",
      "Midst",
      "Of Course",
      "Krambambuli",
    ],
  },
  {
    id: "140",
    playlist: [
      "Haleakal\\u0101",
      "Dragonfire",
      "Moonstrike's Lament",
      "Redwoods",
      "Birthday Crook",
      "Simplistic Glove",
      "Ticket",
      "Our 27th Song",
      "Petite Pete",
      "Smart Flower",
    ],
  },
  {
    id: "139",
    playlist: [
      "Suggested Chicken",
      "Hospital Society",
      "Gold Guitar Theory",
      "And Now the Good News",
      "12 or 66",
      "Moonbeams",
      "Explosions",
      "Blue Orange",
      "Desk Crack",
      "Opalescence ",
    ],
  },
  {
    id: "138",
    playlist: [
      "Mountains of the M",
      "Self-absorbed Husbands",
      "Puppies",
      "Rocketships",
      "Untitled 2",
      "Ku-Tut",
      "A9",
      "Late & Stained",
      "Reload",
      "Moana",
    ],
  },
  {
    id: "137",
    playlist: [
      "You First",
      "Raiya Sees",
      "Spiraling Excitement",
      "Cranberry Crystals",
      "Four Turtles",
      "Needle",
      "K\\u014dkako",
      "Of Course",
      "Ugly Baby",
      "Olivia's Pots",
      "Swashbuckling Squids",
    ],
  },
  {
    id: "136",
    playlist: [
      "Top",
      "Patrick Swayze",
      "Redwoods",
      "Greypeak Range",
      "Current Lamp",
      "Duke's Journey",
      "Spider",
      "The Wave",
      "Ananas comosus",
      "Go!",
      "Sure",
    ],
  },
  {
    id: "135",
    playlist: [
      "Stinky Uncle Steve",
      "McDonald\\u2019s Theory",
      "Kofi",
      "The Wax Post",
      "Spiron Festival",
      "Davy Gravy",
      "Make It Relevant ",
      "And Now the Good News",
      "Blended Together",
      "Degas & Shoal",
      "NNW",
      "Ticket",
    ],
  },
  {
    id: "134",
    playlist: [
      "Cochemeleon",
      "Late & Stained",
      "Celsius",
      "Apologies Owed",
      "Midst",
      "Bird's Eye",
      "Our 27th Song",
      "On the Low Rung",
      "12 or 66",
      "The Tuesday Headache",
      "Fuzzy Fuzzbuzz",
      "Biker",
    ],
  },
  {
    id: "133",
    playlist: [
      "Untitled 1",
      "Harmony Vase",
      "Of Course",
      "Doge Meme",
      "Deer Crash",
      "Birthday Crook",
      "Reload",
      "High School",
      "Explosions",
      "The Big Green Hill",
      "Waiting for Fred",
      "Tiger mountain",
    ],
  },
  {
    id: "132",
    playlist: [
      "Puppies",
      "Car Fold",
      "Redwoods",
      "Mock Orange Blossom",
      "Duke's Revenge",
      "You First",
      "Blue Orange",
      "Petite Pete",
      "Eyes Floating in Cups",
      "Grey Clouds",
      "Krambambuli",
    ],
  },
  {
    id: "131",
    playlist: [
      "Self-absorbed Husbands",
      "Spider",
      "Moonbeams",
      "The First Show",
      "Kiwi Kea",
      "Moonstrike's Lament",
      "Make It Relevant ",
      "Toothbrush Fight",
      "Ugly Baby",
      "Reload",
      "Sunbird Stream",
    ],
  },
  {
    id: "130",
    playlist: [
      "F-12",
      "Simplistic Glove",
      "Raiya Sees",
      "Untitled 3",
      "Suggested Chicken",
      "Current Lamp",
      "Ticket",
      "Late & Stained",
      "Mountains of the M",
      "Blue Orange",
      "The Turning Machine",
      "Of Course",
    ],
  },
  {
    id: "129",
    playlist: [
      "Desk Crack",
      "McDonald\\u2019s Theory",
      "Redwoods",
      "Smart Flower",
      "Ananas comosus",
      "The Tuesday Headache",
      "Cranberry Crystals",
      "Lavender",
      "Roadlife",
      "Harmony Vase",
      "Shh I'm Thinking",
      "Reload",
      "Untitled 2",
    ],
  },
  {
    id: "128",
    playlist: [
      "Four Turtles",
      "Mountains of the M",
      "Tiger mountain",
      "Hospital Society",
      "Rocketships",
      "Bird's Eye",
      "Haleakal\\u0101",
      "Sure",
      "Stinky Uncle Steve",
      "Spider",
      "You First",
    ],
  },
  {
    id: "127",
    playlist: [
      "K\\u014dkako",
      "Greypeak Range",
      "Moana",
      "Birthday Crook",
      "Midst",
      "Spiron Festival",
      "Reload",
      "Car Fold",
      "Opalescence ",
      "Make It Relevant ",
      "Of Course",
    ],
  },
  {
    id: "126",
    playlist: [
      "Patrick Swayze",
      "Dragonfire",
      "Our 27th Song",
      "A9",
      "Redwoods",
      "Gold Guitar Theory",
      "Swashbuckling Squids",
      "The Wax Post",
      "Moonbeams",
      "Untitled 1",
      "Petite Pete",
      "Wave to the Wind",
      "Ticket",
    ],
  },
  {
    id: "125",
    playlist: [
      "Olivia's Pots",
      "Top",
      "Biker",
      "Spider",
      "Reload",
      "High School",
      "Ku-Tut",
      "Self-absorbed Husbands",
      "Davy Gravy",
      "Krambambuli",
      "The Tuesday Headache",
      "Blue Orange",
    ],
  },
  {
    id: "124",
    playlist: [
      "Moonstrike's Lament",
      "Celsius",
      "The Big Green Hill",
      "Make It Relevant ",
      "Harmony Vase",
      "Degas & Shoal",
      "Spiraling Excitement",
      "Current Lamp",
      "Eyes Floating in Cups",
      "Tiger mountain",
      "Duke's Journey",
      "Moonbeams",
    ],
  },
  {
    id: "123",
    playlist: [
      "Sunbird Stream",
      "Hospital Society",
      "Ananas comosus",
      "Deer Crash",
      "Fuzzy Fuzzbuzz",
      "Car Fold",
      "Raiya Sees",
      "Gold Guitar Theory",
      "Duke's Revenge",
      "Blue Orange",
      "NNW",
    ],
  },
  {
    id: "122",
    playlist: [
      "And Now the Good News",
      "Spider",
      "Ugly Baby",
      "Of Course",
      "McDonald\\u2019s Theory",
      "Puppies",
      "Make It Relevant ",
      "Explosions",
      "12 or 66",
      "You First",
      "Redwoods",
      "Late & Stained",
      "Go!",
    ],
  },
  {
    id: "121",
    playlist: [
      "K\\u014dkako",
      "Ticket",
      "Harmony Vase",
      "On the Low Rung",
      "Blue Orange",
      "Desk Crack",
      "Stinky Uncle Steve",
      "Self-absorbed Husbands",
      "Kofi",
      "The First Show",
      "The Wave",
      "Suggested Chicken",
    ],
  },
  {
    id: "120",
    playlist: [
      "F-12",
      "Cochemeleon",
      "Cranberry Crystals",
      "Mock Orange Blossom",
      "Mountains of the M",
      "Petite Pete",
      "Degas & Shoal",
      "Toothbrush Fight",
      "Birthday Crook",
      "Reload",
      "NNW",
    ],
  },
  {
    id: "119",
    playlist: [
      "Waiting for Fred",
      "Kiwi Kea",
      "Greypeak Range",
      "Hospital Society",
      "Untitled 2",
      "The Tuesday Headache",
      "Bird's Eye",
      "Blue Orange",
      "Current Lamp",
      "Simplistic Glove",
      "Patrick Swayze",
    ],
  },
  {
    id: "118",
    playlist: [
      "Doge Meme",
      "Our 27th Song",
      "Gold Guitar Theory",
      "Sure",
      "Reload",
      "Spiron Festival",
      "Suggested Chicken",
      "Krambambuli",
      "Smart Flower",
      "Tiger mountain",
      "Untitled 3",
    ],
  },
  {
    id: "117",
    playlist: [
      "Birthday Crook",
      "Shh I'm Thinking",
      "Moonbeams",
      "Car Fold",
      "Blue Orange",
      "Midst",
      "Desk Crack",
      "The Wax Post",
      "Four Turtles",
      "Biker",
      "Grey Clouds",
    ],
  },
  {
    id: "116",
    playlist: [
      "Simplistic Glove",
      "The Turning Machine",
      "High School",
      "Rocketships",
      "Toothbrush Fight",
      "Reload",
      "Untitled 1",
      "Self-absorbed Husbands",
      "Apologies Owed",
      "Raiya Sees",
      "Eyes Floating in Cups",
      "Lavender",
    ],
  },
  {
    id: "115",
    playlist: [
      "Moana",
      "NNW",
      "Ticket",
      "Davy Gravy",
      "Moonstrike's Lament",
      "Ananas comosus",
      "Haleakal\\u0101",
      "Suggested Chicken",
      "Hospital Society",
      "Roadlife",
      "Swashbuckling Squids",
      "Blue Orange",
    ],
  },
  {
    id: "114",
    playlist: [
      "Gold Guitar Theory",
      "Degas & Shoal",
      "Duke's Revenge",
      "The Tuesday Headache",
      "Celsius",
      "Top",
      "Opalescence ",
      "Birthday Crook",
      "Reload",
      "Harmony Vase",
      "A9",
    ],
  },
  {
    id: "113",
    playlist: [
      "Sunbird Stream",
      "The Big Green Hill",
      "K\\u014dkako",
      "Petite Pete",
      "Current Lamp",
      "Simplistic Glove",
      "Blue Orange",
      "Desk Crack",
      "Tiger mountain",
      "Olivia's Pots",
    ],
  },
  {
    id: "112",
    playlist: [
      "Krambambuli",
      "Reload",
      "Dragonfire",
      "Stinky Uncle Steve",
      "Toothbrush Fight",
      "Suggested Chicken",
      "Mountains of the M",
      "Deer Crash",
      "Car Fold",
      "Patrick Swayze",
      "Blended Together",
    ],
  },
  {
    id: "111",
    playlist: [
      "The First Show",
      "Blue Orange",
      "Cranberry Crystals",
      "Moonbeams",
      "Birthday Crook",
      "Fuzzy Fuzzbuzz",
      "Self-absorbed Husbands",
      "Hospital Society",
      "Greypeak Range",
      "Our 27th Song",
    ],
  },
  {
    id: "110",
    playlist: [
      "Spiraling Excitement",
      "Wave to the Wind",
      "Reload",
      "Needle",
      "The Wax Post",
      "Simplistic Glove",
      "F-12",
      "Spiron Festival",
      "The Wave",
      "High School",
      "Gold Guitar Theory",
      "Bird's Eye",
      "NNW",
    ],
  },
  {
    id: "109",
    playlist: [
      "Degas & Shoal",
      "Smart Flower",
      "Desk Crack",
      "Midst",
      "Kiwi Kea",
      "Ku-Tut",
      "On the Low Rung",
      "Moonstrike's Lament",
      "Blue Orange",
      "Eyes Floating in Cups",
      "Suggested Chicken",
      "Duke's Journey",
    ],
  },
  {
    id: "108",
    playlist: [
      "The Tuesday Headache",
      "Mock Orange Blossom",
      "Untitled 1",
      "Ananas comosus",
      "Tiger mountain",
      "Sure",
      "Biker",
      "Toothbrush Fight",
      "Reload",
      "Birthday Crook",
      "Untitled 2",
    ],
  },
  {
    id: "107",
    playlist: [
      "Simplistic Glove",
      "Blue Orange",
      "Moonbeams",
      "Krambambuli",
      "Petite Pete",
      "Duke's Revenge",
      "Davy Gravy",
      "Rocketships",
      "Shh I'm Thinking",
      "Untitled 3",
      "Waiting for Fred",
      "Cochemeleon",
      "Kofi",
    ],
  },
  {
    id: "106",
    playlist: [
      "Desk Crack",
      "NNW",
      "Reload",
      "Self-absorbed Husbands",
      "Mountains of the M",
      "Sunbird Stream",
      "A9",
      "Haleakal\\u0101",
      "The Turning Machine",
      "Grey Clouds",
      "Doge Meme",
    ],
  },
  {
    id: "105",
    playlist: [
      "Toothbrush Fight",
      "Lavender",
      "Degas & Shoal",
      "Blue Orange",
      "Spiron Festival",
      "Cranberry Crystals",
      "Deer Crash",
      "Olivia's Pots",
      "Moana",
      "Opalescence ",
      "Four Turtles",
    ],
  },
  {
    id: "104",
    playlist: [
      "Our 27th Song",
      "Reload",
      "Stinky Uncle Steve",
      "The Big Green Hill",
      "Biker",
      "High School",
      "Celsius",
      "Swashbuckling Squids",
      "Eyes Floating in Cups",
      "Moonbeams",
      "Apologies Owed",
    ],
  },
  {
    id: "103",
    playlist: [
      "Roadlife",
      "Untitled 1",
      "Blue Orange",
      "Patrick Swayze",
      "The Wax Post",
      "K\\u014dkako",
      "Self-absorbed Husbands",
      "Midst",
      "Top",
      "Greypeak Range",
      "Krambambuli",
    ],
  },
  {
    id: "102",
    playlist: [
      "Simplistic Glove",
      "Harmony Vase",
      "Raiya Sees",
      "Suggested Chicken",
      "Desk Crack",
      "Reload",
      "Birthday Crook",
      "Hospital Society",
      "Gold Guitar Theory",
      "Car Fold",
      "Toothbrush Fight",
      "Ticket",
      "Current Lamp",
    ],
  },
  {
    id: "101",
    playlist: [
      "Lavender",
      "Blue Orange",
      "Dragonfire",
      "Fuzzy Fuzzbuzz",
      "Moonstrike's Lament",
      "Ananas comosus",
      "Petite Pete",
      "Moonbeams",
      "Bird's Eye",
      "NNW",
    ],
  },
  {
    id: "100",
    playlist: [
      "The First Show",
      "Untitled 2",
      "Ticket",
      "Mountains of the M",
      "F-12",
      "Davy Gravy",
      "Smart Flower",
      "Biker",
      "Self-absorbed Husbands",
      "Blended Together",
      "Degas & Shoal",
    ],
  },
  {
    id: "99",
    playlist: [
      "Sure",
      "Untitled 1",
      "Kiwi Kea",
      "Duke's Revenge",
      "Sunbird Stream",
      "Spiron Festival",
      "Bird's Eye",
      "Eyes Floating in Cups",
      "The Wave",
    ],
  },
  {
    id: "98",
    playlist: [
      "K\\u014dkako",
      "A9",
      "Stinky Uncle Steve",
      "Rocketships",
      "Moonbeams",
      "Deer Crash",
      "Self-absorbed Husbands",
      "Needle",
      "Ku-Tut",
    ],
  },
  {
    id: "97",
    playlist: [
      "Petite Pete",
      "Patrick Swayze",
      "Biker",
      "Opalescence ",
      "On the Low Rung",
      "Cochemeleon",
      "Swashbuckling Squids",
      "Eyes Floating in Cups",
    ],
  },
  {
    id: "96",
    playlist: [
      "Raiya Sees",
      "Bird's Eye",
      "Cranberry Crystals",
      "Doge Meme",
      "Ananas comosus",
      "Self-absorbed Husbands",
      "The Big Green Hill",
      "Greypeak Range",
      "Smart Flower",
    ],
  },
  {
    id: "95",
    playlist: [
      "Eyes Floating in Cups",
      "Davy Gravy",
      "Shh I'm Thinking",
      "The Wax Post",
      "Moonbeams",
      "Sunbird Stream",
      "Mock Orange Blossom",
      "Haleakal\\u0101",
      "Spiraling Excitement",
      "Moana",
      "Celsius",
      "Duke's Journey",
      "Moonstrike's Lament",
    ],
  },
  {
    id: "94",
    playlist: [
      "Swashbuckling Squids",
      "Mountains of the M",
      "Smart Flower",
      "Fuzzy Fuzzbuzz",
      "High School",
      "Waiting for Fred",
      "Deer Crash",
      "Grey Clouds",
      "Spiron Festival",
      "Midst",
      "Olivia's Pots",
    ],
  },
  {
    id: "93",
    playlist: [
      "Untitled 1",
      "Stinky Uncle Steve",
      "Lavender",
      "Krambambuli",
      "Untitled 2",
      "Self-absorbed Husbands",
      "The Turning Machine",
      "Biker",
      "Our 27th Song",
      "Untitled 3",
      "Reload",
      "Four Turtles",
    ],
  },
  {
    id: "92",
    playlist: [
      "Top",
      "The Big Green Hill",
      "Moonbeams",
      "Sunbird Stream",
      "Opalescence ",
      "Apologies Owed",
      "Kofi",
      "F-12",
      "Kiwi Kea",
      "Rocketships",
      "Wave to the Wind",
      "Dragonfire",
    ],
  },
  {
    id: "91",
    playlist: [
      "Haleakal\\u0101",
      "Duke's Revenge",
      "K\\u014dkako",
      "Eyes Floating in Cups",
      "Petite Pete",
      "Ananas comosus",
      "Moonstrike's Lament",
      "Roadlife",
      "Mock Orange Blossom",
      "Ticket",
      "Blue Orange",
    ],
  },
  {
    id: "90",
    playlist: [
      "Davy Gravy",
      "Deer Crash",
      "Blended Together",
      "Spiron Festival",
      "Ku-Tut",
      "Self-absorbed Husbands",
      "Moana",
      "The Wave",
      "Cochemeleon",
      "Biker",
      "Greypeak Range",
    ],
  },
  {
    id: "89",
    playlist: [
      "Untitled 2",
      "Doge Meme",
      "Spiraling Excitement",
      "The Wax Post",
      "Grey Clouds",
      "Shh I'm Thinking",
      "Dragonfire",
      "Untitled 3",
      "Rocketships",
      "Olivia's Pots",
      "Fuzzy Fuzzbuzz",
    ],
  },
  {
    id: "88",
    playlist: [
      "Lavender",
      "The First Show",
      "Celsius",
      "Kiwi Kea",
      "A9",
      "Duke's Journey",
      "Bird's Eye",
      "Sure",
      "Smart Flower",
      "Our 27th Song",
      "Stinky Uncle Steve",
      "Patrick Swayze",
    ],
  },
  {
    id: "87",
    playlist: [
      "Reload",
      "Raiya Sees",
      "Self-absorbed Husbands",
      "Krambambuli",
      "Ticket",
      "Blue Orange",
      "Moonbeams",
      "Midst",
      "High School",
      "Biker",
      "Untitled 1",
      "Ananas comosus",
      "Eyes Floating in Cups",
      "Petite Pete",
      "Moonstrike's Lament",
    ],
  },
  {
    id: "86",
    playlist: [
      "Mock Orange Blossom",
      "Kofi",
      "Needle",
      "On the Low Rung",
      "High School",
      "F-12",
      "Apologies Owed",
      "Greypeak Range",
      "Spiron Festival",
      "K\\u014dkako",
      "Four Turtles",
      "Sunbird Stream",
      "Cranberry Crystals",
    ],
  },
  {
    id: "85",
    playlist: [
      "Waiting for Fred",
      "Self-absorbed Husbands",
      "Moana",
      "F-12",
      "Cranberry Crystals",
      "The Turning Machine",
      "Duke's Revenge",
      "Midst",
      "Mountains of the M",
      "Sunbird Stream",
      "Deer Crash",
      "Opalescence ",
      "Davy Gravy",
    ],
  },
  {
    id: "84",
    playlist: [
      "Roadlife",
      "Petite Pete",
      "Midst",
      "Moonstrike's Lament",
      "Haleakal\\u0101",
      "Davy Gravy",
      "The Big Green Hill",
      "Reload",
      "Apologies Owed",
      "Spiron Festival",
      "Swashbuckling Squids",
      "Needle",
      "Cochemeleon",
      "Mountains of the M",
    ],
  },
  {
    id: "83",
    playlist: [
      "Mock Orange Blossom",
      "Deer Crash",
      "Fuzzy Fuzzbuzz",
      "The Big Green Hill",
      "Moana",
      "The Wax Post",
      "K\\u014dkako",
      "Rocketships",
      "Roadlife",
      "Mountains of the M",
      "Olivia's Pots",
      "Wave to the Wind",
      "Untitled 2",
      "Cranberry Crystals",
    ],
  },
  {
    id: "82",
    playlist: [
      "Stinky Uncle Steve",
      "Shh I'm Thinking",
      "Four Turtles",
      "Swashbuckling Squids",
      "Moana",
      "Waiting for Fred",
      "Untitled 3",
      "Mountains of the M",
      "Rocketships",
      "The Wave",
      "Opalescence ",
      "Ku-Tut",
      "On the Low Rung",
      "Mock Orange Blossom",
      "The Wax Post",
    ],
  },
  {
    id: "81",
    playlist: [
      "Biker",
      "Midst",
      "Doge Meme",
      "Dragonfire",
      "Reload",
      "Untitled 1",
      "Four Turtles",
      "Kofi",
      "Grey Clouds",
      "Cranberry Crystals",
      "Untitled 2",
      "Moana",
    ],
  },
  {
    id: "80",
    playlist: [
      "On the Low Rung",
      "Moonbeams",
      "Moana",
      "Kofi",
      "Cranberry Crystals",
      "Apologies Owed",
      "Smart Flower",
      "Waiting for Fred",
      "Ananas comosus",
      "Untitled 1",
      "Our 27th Song",
      "Bird's Eye",
      "Greypeak Range",
      "Biker",
      "Petite Pete",
    ],
  },
  {
    id: "79",
    playlist: [
      "Opalescence ",
      "Ku-Tut",
      "Krambambuli",
      "Spiraling Excitement",
      "K\\u014dkako",
      "Blended Together",
      "Blue Orange",
      "Petite Pete",
      "Roadlife",
      "The Wax Post",
      "Patrick Swayze",
    ],
  },
  {
    id: "78",
    playlist: [
      "Top",
      "Mountains of the M",
      "On the Low Rung",
      "Spiraling Excitement",
      "Untitled 2",
      "Kofi",
      "Haleakal\\u0101",
      "Swashbuckling Squids",
      "Petite Pete",
      "Blue Orange",
      "Spiron Festival",
      "Ananas comosus",
      "F-12",
    ],
  },
  {
    id: "77",
    playlist: [
      "Fuzzy Fuzzbuzz",
      "Biker",
      "Ticket",
      "Krambambuli",
      "Cochemeleon",
      "Mountains of the M",
      "Doge Meme",
      "Ku-Tut",
      "Sunbird Stream",
      "Raiya Sees",
      "Sure",
      "The Big Green Hill",
      "Blue Orange",
    ],
  },
  {
    id: "76",
    playlist: [
      "Cochemeleon",
      "Grey Clouds",
      "Untitled 3",
      "Apologies Owed",
      "On the Low Rung",
      "A9",
      "Rocketships",
      "Four Turtles",
      "Ticket",
      "Shh I'm Thinking",
      "Our 27th Song",
      "Ku-Tut",
      "Midst",
      "Untitled 1",
      "Davy Gravy",
    ],
  },
  {
    id: "75",
    playlist: [
      "Untitled 3",
      "Shh I'm Thinking",
      "Apologies Owed",
      "Ananas comosus",
      "F-12",
      "Swashbuckling Squids",
      "Fuzzy Fuzzbuzz",
      "Waiting for Fred",
      "Wave to the Wind",
      "Midst",
      "Untitled 2",
    ],
  },
  {
    id: "74",
    playlist: [
      "Needle",
      "Moana",
      "Blended Together",
      "Kiwi Kea",
      "Sure",
      "Doge Meme",
      "Moonbeams",
      "Duke's Revenge",
      "K\\u014dkako",
      "High School",
      "Cranberry Crystals",
      "Swashbuckling Squids",
      "Cochemeleon",
      "Reload",
    ],
  },
  {
    id: "73",
    playlist: [
      "Patrick Swayze",
      "Duke's Journey",
      "Shh I'm Thinking",
      "Untitled 1",
      "Ku-Tut",
      "Mountains of the M",
      "Raiya Sees",
      "Deer Crash",
      "Blended Together",
      "Moonstrike's Lament",
      "Greypeak Range",
    ],
  },
  {
    id: "72",
    playlist: [
      "Wave to the Wind",
      "On the Low Rung",
      "A9",
      "Greypeak Range",
      "Haleakal\\u0101",
      "Deer Crash",
      "Cochemeleon",
      "Spiraling Excitement",
      "Fuzzy Fuzzbuzz",
      "Spiron Festival",
      "K\\u014dkako",
      "Davy Gravy",
      "Ananas comosus",
      "Krambambuli",
    ],
  },
  {
    id: "71",
    playlist: [
      "Waiting for Fred",
      "Sunbird Stream",
      "Reload",
      "Moana",
      "Stinky Uncle Steve",
      "Our 27th Song",
      "Mountains of the M",
      "Kofi",
      "On the Low Rung",
      "Untitled 1",
      "The Wax Post",
      "Opalescence ",
      "Dragonfire",
      "Doge Meme",
      "Top",
    ],
  },
  {
    id: "70",
    playlist: [
      "Shh I'm Thinking",
      "Eyes Floating in Cups",
      "Grey Clouds",
      "The Wave",
      "Olivia's Pots",
      "Spiraling Excitement",
      "Ananas comosus",
      "Top",
      "Celsius",
      "A9",
      "The Big Green Hill",
      "Opalescence ",
      "High School",
      "Ku-Tut",
    ],
  },
  {
    id: "69",
    playlist: [
      "A9",
      "Moonbeams",
      "Deer Crash",
      "Smart Flower",
      "The Turning Machine",
      "Untitled 3",
      "Olivia's Pots",
      "Celsius",
      "Petite Pete",
      "Swashbuckling Squids",
      "Spiron Festival",
      "Grey Clouds",
    ],
  },
  {
    id: "68",
    playlist: [
      "F-12",
      "Bird's Eye",
      "Blue Orange",
      "Cochemeleon",
      "Grey Clouds",
      "Midst",
      "Smart Flower",
      "Ananas comosus",
      "Kiwi Kea",
      "Waiting for Fred",
      "Biker",
      "Petite Pete",
    ],
  },
  {
    id: "67",
    playlist: [
      "Mountains of the M",
      "K\\u014dkako",
      "Smart Flower",
      "F-12",
      "Moana",
      "Kofi",
      "The First Show",
      "Petite Pete",
      "Ananas comosus",
      "Kiwi Kea",
      "Blended Together",
    ],
  },
  {
    id: "66",
    playlist: [
      "Top",
      "Cochemeleon",
      "Moonstrike's Lament",
      "Petite Pete",
      "Mountains of the M",
      "Sure",
      "A9",
      "The Turning Machine",
      "Celsius",
      "Moana",
      "Untitled 2",
      "Shh I'm Thinking",
    ],
  },
  {
    id: "65",
    playlist: [
      "Top",
      "K\\u014dkako",
      "Spiraling Excitement",
      "On the Low Rung",
      "Raiya Sees",
      "The Big Green Hill",
      "Roadlife",
      "Ku-Tut",
      "Kiwi Kea",
      "Midst",
      "Sure",
      "Ticket",
      "Fuzzy Fuzzbuzz",
      "Moonstrike's Lament",
      "Waiting for Fred",
    ],
  },
  {
    id: "64",
    playlist: [
      "Raiya Sees",
      "A9",
      "Moonbeams",
      "Wave to the Wind",
      "Cranberry Crystals",
      "Cochemeleon",
      "Petite Pete",
      "Duke's Journey",
      "Davy Gravy",
      "Spiron Festival",
      "Stinky Uncle Steve",
    ],
  },
  {
    id: "63",
    playlist: [
      "The Turning Machine",
      "On the Low Rung",
      "Haleakal\\u0101",
      "Fuzzy Fuzzbuzz",
      "Mountains of the M",
      "F-12",
      "Greypeak Range",
      "Reload",
      "Davy Gravy",
      "Grey Clouds",
      "Patrick Swayze",
      "Needle",
      "Sure",
      "Deer Crash",
    ],
  },
  {
    id: "62",
    playlist: [
      "Rocketships",
      "Doge Meme",
      "Four Turtles",
      "Untitled 3",
      "Untitled 1",
      "Midst",
      "Apologies Owed",
      "Haleakal\\u0101",
      "Cochemeleon",
      "Kiwi Kea",
      "Greypeak Range",
      "High School",
      "The Turning Machine",
    ],
  },
  {
    id: "61",
    playlist: [
      "Swashbuckling Squids",
      "On the Low Rung",
      "Untitled 1",
      "K\\u014dkako",
      "Untitled 3",
      "Lavender",
      "Krambambuli",
      "Davy Gravy",
      "Cochemeleon",
      "Midst",
      "The Big Green Hill",
      "The Turning Machine",
      "Eyes Floating in Cups",
      "Shh I'm Thinking",
      "Ananas comosus",
    ],
  },
  {
    id: "60",
    playlist: [
      "Sunbird Stream",
      "Grey Clouds",
      "Swashbuckling Squids",
      "Stinky Uncle Steve",
      "Roadlife",
      "Davy Gravy",
      "Apologies Owed",
      "Eyes Floating in Cups",
      "Petite Pete",
      "Moonbeams",
      "Rocketships",
      "Fuzzy Fuzzbuzz",
      "Self-absorbed Husbands",
    ],
  },
  {
    id: "59",
    playlist: [
      "Bird's Eye",
      "Don't Let the Air Out of My Tires",
      "Grey Clouds",
      "Roadlife",
      "Ku-Tut",
      "Celsius",
      "Kofi",
      "Self-absorbed Husbands",
      "The Wax Post",
      "Our 27th Song",
      "Cochemeleon",
      "Guyute",
      "Olivia's Pots",
    ],
  },
  {
    id: "58",
    playlist: [
      "Mountains of the M",
      "Moana",
      "Bird's Eye",
      "Lavender",
      "Cochemeleon",
      "Ananas comosus",
      "Biker",
      "The Big Green Hill",
      "Kofi",
      "Haleakal\\u0101",
    ],
  },
  {
    id: "57",
    playlist: [
      "Raiya Sees",
      "Ticket",
      "Duke's Revenge",
      "Spiraling Excitement",
      "Olivia's Pots",
      "Kiwi Kea",
      "A9",
      "Celsius",
      "The Turning Machine",
      "Four Turtles",
      "The Wax Post",
      "The Wave",
      "Mock Orange Blossom",
      "Greypeak Range",
      "Blue Orange",
    ],
  },
  {
    id: "56",
    playlist: [
      "Needle",
      "Cranberry Crystals",
      "The First Show",
      "Celsius",
      "Blue Orange",
      "Four Turtles",
      "Waiting for Fred",
      "On the Low Rung",
      "Midst",
      "Reload",
      "Olivia's Pots",
      "Shh I'm Thinking",
    ],
  },
  {
    id: "55",
    playlist: [
      "Cranberry Crystals",
      "Four Turtles",
      "Olivia's Pots",
      "Shh I'm Thinking",
      "Duke's Revenge",
      "Doge Meme",
      "The First Show",
      "Ku-Tut",
      "Dragonfire",
      "Our 27th Song",
      "Deer Crash",
      "Blended Together",
      "Top",
    ],
  },
  {
    id: "54",
    playlist: [
      "Smart Flower",
      "Dragonfire",
      "Spiraling Excitement",
      "Mock Orange Blossom",
      "K\\u014dkako",
      "Kiwi Kea",
      "Doge Meme",
      "Opalescence ",
      "Deer Crash",
      "Shh I'm Thinking",
    ],
  },
  {
    id: "53",
    playlist: [
      "Midst",
      "Greypeak Range",
      "The Wave",
      "The Turning Machine",
      "Ku-Tut",
      "What a Wonderful World",
      "Blended Together",
      "Patrick Swayze",
      "Reload",
      "A9",
      "Sure",
      "Krambambuli",
      "Blue Orange",
      "Waiting for Fred",
    ],
  },
  {
    id: "52",
    playlist: [
      "Needle",
      "Another Brick in the Wall",
      "Krambambuli",
      "Waiting for Fred",
      "Celsius",
      "Blended Together",
      "Little Bones",
      "The Turning Machine",
      "Sure",
      "The Wave",
      "Midst",
      "On the Low Rung",
      "The First Show",
      "Raiya Sees",
      "Cranberry Crystals",
    ],
  },
  {
    id: "51",
    playlist: [
      "Ku-Tut",
      "Reload",
      "Greypeak Range",
      "On the Low Rung",
      "The Turning Machine",
      "Blended Together",
      "Patrick Swayze",
      "Sure",
      "Guyute",
      "Spiron Festival",
      "Krambambuli",
      "A9",
      "Needle",
      "The Wave",
    ],
  },
  {
    id: "50",
    playlist: [
      "The Wave",
      "Needle",
      "Greypeak Range",
      "Ku-Tut",
      "Blended Together",
      "Duke's Journey",
      "Top",
      "Cranberry Crystals",
      "Four Turtles",
      "Raiya Sees",
      "Our 27th Song",
      "The First Show",
    ],
  },
  {
    id: "49",
    playlist: [
      "Blue Orange",
      "Our 27th Song",
      "Ku-Tut",
      "Blended Together",
      "The Wax Post",
      "Midst",
      "Wave to the Wind",
      "Sure",
      "Cranberry Crystals",
      "Don't Let the Air Out of My Tires",
      "Patrick Swayze",
      "Duke's Revenge",
    ],
  },
  {
    id: "48",
    playlist: [
      "The Wave",
      "Don't Let the Air Out of My Tires",
      "Raiya Sees",
      "On the Low Rung",
      "Duke's Journey",
      "A9",
      "Top",
      "Cranberry Crystals",
      "Another Brick in the Wall",
      "Midst",
      "Ticket",
      "Little Bones",
      "Our 27th Song",
      "The First Show",
      "High School",
    ],
  },
  {
    id: "47",
    playlist: [
      "Duke's Revenge",
      "Blended Together",
      "Olivia's Pots",
      "Another Brick in the Wall",
      "Patrick Swayze",
      "The Turning Machine",
      "Cranberry Crystals",
      "Little Bones",
      "High School",
      "Midst",
      "A9",
      "On the Low Rung",
      "Greypeak Range",
      "Duke's Journey",
    ],
  },
  {
    id: "46",
    playlist: [
      "Don't Let the Air Out of My Tires",
      "Needle",
      "Celsius",
      "Our 27th Song",
      "The Wax Post",
      "Raiya Sees",
      "Patrick Swayze",
      "Blue Orange",
      "Top",
      "The Turning Machine",
      "Another Brick in the Wall",
      "Cranberry Crystals",
    ],
  },
  {
    id: "45",
    playlist: [
      "Greypeak Range",
      "Needle",
      "Ticket",
      "Celsius",
      "Wave to the Wind",
      "The Turning Machine",
      "Spiron Festival",
      "Blended Together",
      "Guyute",
      "What a Wonderful World",
      "F-12",
      "Krambambuli",
      "Another Brick in the Wall",
      "Top",
      "High School",
    ],
  },
  {
    id: "44",
    playlist: [
      "Moonstrike's Lament",
      "Blue Orange",
      "Ku-Tut",
      "Celsius",
      "Little Bones",
      "Raiya Sees",
      "Wave to the Wind",
      "What a Wonderful World",
      "Olivia's Pots",
      "Duke's Journey",
      "Waiting for Fred",
      "Greypeak Range",
      "Cranberry Crystals",
      "Pixilxil",
    ],
  },
  {
    id: "43",
    playlist: [
      "High School",
      "Patrick Swayze",
      "Greypeak Range",
      "Moonstrike's Lament",
      "Sure",
      "The Wax Post",
      "The Wave",
      "On the Low Rung",
      "Four Turtles",
      "Cranberry Crystals",
      "A9",
    ],
  },
  {
    id: "42",
    playlist: [
      "Patrick Swayze",
      "Blended Together",
      "Moonstrike's Lament",
      "Midst",
      "The Wave",
      "Waiting for Fred",
      "Our 27th Song",
      "Little Bones",
      "Pixilxil",
      "Celsius",
      "Spiron Festival",
      "Krambambuli",
      "What a Wonderful World",
    ],
  },
  {
    id: "41",
    playlist: [
      "Four Turtles",
      "F-12",
      "Another Brick in the Wall",
      "The Wave",
      "Wave to the Wind",
      "High School",
      "Blended Together",
      "Olivia's Pots",
      "On the Low Rung",
      "Duke's Revenge",
      "Little Bones",
      "Ku-Tut",
      "Waiting for Fred",
      "Cranberry Crystals",
    ],
  },
  {
    id: "40",
    playlist: [
      "The Wave",
      "The First Show",
      "A9",
      "Wave to the Wind",
      "High School",
      "Greypeak Range",
      "Four Turtles",
      "Ku-Tut",
      "Duke's Revenge",
      "Don't Let the Air Out of My Tires",
      "Patrick Swayze",
      "Duke's Journey",
    ],
  },
  {
    id: "39",
    playlist: [
      "Top",
      "Ku-Tut",
      "High School",
      "The Turning Machine",
      "The Wax Post",
      "Duke's Revenge",
      "Celsius",
      "Greypeak Range",
      "Duke's Journey",
      "Midst",
      "Blended Together",
      "Another Brick in the Wall",
      "F-12",
    ],
  },
  {
    id: "38",
    playlist: [
      "Midst",
      "Guyute",
      "Moonstrike's Lament",
      "Reload",
      "Celsius",
      "Patrick Swayze",
      "The Wax Post",
      "Sure",
      "Don't Let the Air Out of My Tires",
      "Duke's Revenge",
      "Top",
      "Little Bones",
      "Cranberry Crystals",
      "Blue Orange",
    ],
  },
  {
    id: "37",
    playlist: [
      "Wave to the Wind",
      "Guyute",
      "Little Bones",
      "On the Low Rung",
      "Cranberry Crystals",
      "Moonstrike's Lament",
      "Top",
      "Pixilxil",
      "Krambambuli",
      "The Wax Post",
      "Raiya Sees",
    ],
  },
  {
    id: "36",
    playlist: [
      "Blue Orange",
      "Duke's Revenge",
      "Little Bones",
      "Celsius",
      "The First Show",
      "What a Wonderful World",
      "Guyute",
      "Needle",
      "Top",
      "Raiya Sees",
      "High School",
      "The Wax Post",
      "Waiting for Fred",
      "The Wave",
      "A9",
    ],
  },
  {
    id: "35",
    playlist: [
      "High School",
      "Patrick Swayze",
      "The First Show",
      "Top",
      "Duke's Journey",
      "Celsius",
      "Don't Let the Air Out of My Tires",
      "Ticket",
      "Krambambuli",
      "Pixilxil",
      "Sure",
      "Duke's Revenge",
      "Greypeak Range",
    ],
  },
  {
    id: "34",
    playlist: [
      "The First Show",
      "Ticket",
      "Ku-Tut",
      "The Wax Post",
      "Cranberry Crystals",
      "Four Turtles",
      "Our 27th Song",
      "Another Brick in the Wall",
      "Don't Let the Air Out of My Tires",
      "Midst",
      "What a Wonderful World",
      "Blue Orange",
      "A9",
    ],
  },
  {
    id: "33",
    playlist: [
      "What a Wonderful World",
      "Waiting for Fred",
      "The First Show",
      "Sure",
      "High School",
      "Patrick Swayze",
      "Pixilxil",
      "Krambambuli",
      "Reload",
    ],
  },
  {
    id: "32",
    playlist: [
      "Blue Orange",
      "Ku-Tut",
      "On the Low Rung",
      "Moonstrike's Lament",
      "The Wax Post",
      "Our 27th Song",
      "Duke's Revenge",
      "Midst",
      "Guyute",
      "Ticket",
    ],
  },
  {
    id: "31",
    playlist: [
      "The Wave",
      "A9",
      "High School",
      "Celsius",
      "Cranberry Crystals",
      "Pixilxil",
      "Top",
      "Krambambuli",
      "Reload",
    ],
  },
  {
    id: "30",
    playlist: [
      "Blue Orange",
      "Olivia's Pots",
      "The Wax Post",
      "Sure",
      "Midst",
      "Patrick Swayze",
      "Duke's Journey",
      "Duke's Revenge",
    ],
  },
  {
    id: "29",
    playlist: [
      "Pixilxil",
      "Raiya Sees",
      "Krambambuli",
      "Ticket",
      "High School",
      "Greypeak Range",
      "Spiron Festival",
      "Cranberry Crystals",
    ],
  },
  {
    id: "28",
    playlist: [
      "Our 27th Song",
      "The Wax Post",
      "Moonstrike's Lament",
      "The Turning Machine",
      "Patrick Swayze",
      "Celsius",
      "Reload",
      "Blue Orange",
    ],
  },
  {
    id: "27",
    playlist: [
      "Olivia's Pots",
      "Ku-Tut",
      "Spiron Festival",
      "Duke's Journey",
      "Raiya Sees",
      "The Wax Post",
      "The Turning Machine",
      "Greypeak Range",
      "Cranberry Crystals",
      "Moonstrike's Lament",
    ],
  },
  {
    id: "26",
    playlist: [
      "Krambambuli",
      "Reload",
      "Top",
      "Little Bones",
      "Pixilxil",
      "Sure",
      "Needle",
      "Wave to the Wind",
      "Blue Orange",
      "Ticket",
    ],
  },
  {
    id: "25",
    playlist: [
      "Blue Orange",
      "A9",
      "Celsius",
      "Midst",
      "High School",
      "Our 27th Song",
      "Four Turtles",
      "Patrick Swayze",
      "Ticket",
      "The Wave",
    ],
  },
  {
    id: "24",
    playlist: [
      "F-12",
      "Pixilxil",
      "A9",
      "Our 27th Song",
      "Celsius",
      "Patrick Swayze",
      "The First Show",
      "Top",
      "Sure",
      "Reload",
    ],
  },
  {
    id: "23",
    playlist: [
      "Our 27th Song",
      "Ticket",
      "Blue Orange",
      "Midst",
      "Sure",
      "Top",
      "Little Bones",
      "Patrick Swayze",
      "Reload",
    ],
  },
  {
    id: "22",
    playlist: [
      "Blue Orange",
      "Patrick Swayze",
      "Guyute",
      "Waiting for Fred",
      "Ticket",
      "F-12",
      "Pixilxil",
      "High School",
      "Reload",
    ],
  },
  {
    id: "21",
    playlist: [
      "Four Turtles",
      "Ticket",
      "Needle",
      "Don't Let the Air Out of My Tires",
      "Sure",
      "Midst",
      "A9",
      "Patrick Swayze",
      "Little Bones",
      "Blue Orange",
    ],
  },
  {
    id: "20",
    playlist: [
      "A9",
      "Patrick Swayze",
      "Celsius",
      "Top",
      "F-12",
      "Blue Orange",
      "Pixilxil",
      "Reload",
      "High School",
      "Ticket",
    ],
  },
  {
    id: "19",
    playlist: [
      "Another Brick in the Wall",
      "Midst",
      "The First Show",
      "Sure",
      "High School",
      "Patrick Swayze",
      "Blue Orange",
      "Reload",
      "Little Bones",
    ],
  },
  {
    id: "18",
    playlist: [
      "What a Wonderful World",
      "Blue Orange",
      "Top",
      "Patrick Swayze",
      "Celsius",
      "Ticket",
      "Wave to the Wind",
      "Reload",
      "Don't Let the Air Out of My Tires",
    ],
  },
  {
    id: "17",
    playlist: [
      "Little Bones",
      "Midst",
      "High School",
      "Pixilxil",
      "Sure",
      "Ticket",
      "Reload",
      "Blue Orange",
    ],
  },
  {
    id: "16",
    playlist: [
      "Blended Together",
      "On the Low Rung",
      "The Wave",
      "Waiting for Fred",
      "F-12",
      "Four Turtles",
      "The First Show",
      "High School",
    ],
  },
  {
    id: "15",
    playlist: [
      "F-12",
      "Midst",
      "High School",
      "Patrick Swayze",
      "Guyute",
      "Celsius",
    ],
  },
  {
    id: "14",
    playlist: [
      "Needle",
      "Wave to the Wind",
      "Sure",
      "Four Turtles",
      "Reload",
      "Blue Orange",
      "Ticket",
    ],
  },
  {
    id: "13",
    playlist: [
      "Top",
      "Ticket",
      "Waiting for Fred",
      "Pixilxil",
      "Blue Orange",
      "Reload",
      "The First Show",
    ],
  },
  {
    id: "12",
    playlist: [
      "The Wave",
      "On the Low Rung",
      "Blended Together",
      "Wave to the Wind",
      "Duke's Revenge",
      "Blue Orange",
    ],
  },
  {
    id: "11",
    playlist: [
      "Wave to the Wind",
      "Pixilxil",
      "Blue Orange",
      "Ticket",
      "Reload",
      "Sure",
    ],
  },
  {
    id: "10",
    playlist: [
      "Duke's Revenge",
      "The Wave",
      "Ticket",
      "The First Show",
      "Pixilxil",
      "Four Turtles",
      "Reload",
    ],
  },
  {
    id: "9",
    playlist: [
      "Pixilxil",
      "On the Low Rung",
      "Waiting for Fred",
      "Top",
      "Blended Together",
      "Blue Orange",
    ],
  },
  {
    id: "8",
    playlist: [
      "Waiting for Fred",
      "Reload",
      "Ticket",
      "Four Turtles",
      "Duke's Revenge",
      "Blue Orange",
    ],
  },
  {
    id: "7",
    playlist: ["Top", "Four Turtles", "The Wave", "Ticket", "Blue Orange"],
  },
  {
    id: "6",
    playlist: [
      "On the Low Rung",
      "Reload",
      "Sure",
      "The First Show",
      "Blue Orange",
    ],
  },
  {
    id: "5",
    playlist: [
      "Reload",
      "Blended Together",
      "The First Show",
      "Ticket",
      "The Wave",
    ],
  },
  {
    id: "4",
    playlist: ["Sure", "Four Turtles", "Duke's Revenge", "Ticket", "Reload"],
  },
  {
    id: "3",
    playlist: [
      "The Wave",
      "The First Show",
      "Ticket",
      "Reload",
      "Blended Together",
    ],
  },
  {
    id: "2",
    playlist: ["The First Show", "Blended Together", "The Wave", "Ticket"],
  },
  { id: "1", playlist: ["Blended Together", "The Wave", "Ticket"] },
];

export function getPlaylists() {
  return playlists;
}

export function getPlaylist(id) {
  return playlists.find((playlist) => playlist.id === id).playlist;
}
