let Songlists = [
  {
    id: "104",
    name: "Of Course",
    name_phish: "Rift",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Optimistic",
    standard_duration: "100",
    weighting: "100",
  },
  {
    id: "103",
    name: "McDonald\u2019s Theory",
    name_phish: "Round Room",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Staircase",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "102",
    name: "Make It Relevant ",
    name_phish: "Undermind",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "House of Cards",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "101",
    name: "Ugly Baby",
    name_phish: "Birds of a Feather",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Faust Arp",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "100",
    name: "You First",
    name_phish: "Antelope",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Dollars & Cents",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "99",
    name: "12 or 66",
    name_phish: "Back on the Train",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "These Are My Twisted Words",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "98",
    name: "Late & Stained",
    name_phish: "Waste",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "I Will",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "97",
    name: "Explosions",
    name_phish: "My Friend, My Friend",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Yes I Am",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "96",
    name: "Puppies",
    name_phish: "Walls of the Cave",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Jigsaw Falling Into Place",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "95",
    name: "Go!",
    name_phish: "Wading in the Velvet Sea",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Hunting Bears",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "94",
    name: "And Now the Good News",
    name_phish: "Wombat",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Paperbag Writer",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "93",
    name: "Redwoods",
    name_phish: "Simple in a Jar",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "High and Dry",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "92",
    name: "Spider",
    name_phish: "Ghost",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Myxomatosis",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "91",
    name: "Tiger mountain",
    name_phish: "Free",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "Bones",
    standard_duration: "302",
    weighting: "100",
  },
  {
    id: "90",
    name: "The Tuesday Headache",
    name_phish: "Patriochr",
    name_taylorswift: "Gold Rush",
    name_gratefuldead: "Mama Tried",
    name_pearljam: "x",
    name_radiohead: "Treefingers",
    standard_duration: "430",
    weighting: "100",
  },
  {
    id: "89",
    name: "Gold Guitar Theory",
    name_phish: "Gumbo",
    name_taylorswift: "Treacherous",
    name_gratefuldead: "High Time",
    name_pearljam: "Alive",
    name_radiohead: "You and Whose Army?",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "88",
    name: "Harmony Vase",
    name_phish: "McGrupp and the Watchful Horsemasters",
    name_taylorswift: "Never Grow Up",
    name_gratefuldead: "Rosemary",
    name_pearljam: "Faithfull",
    name_radiohead: "Stop Whispering",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "87",
    name: "Simplistic Glove",
    name_phish: "Sparkle",
    name_taylorswift: "Sad Beautiful Tragic",
    name_gratefuldead: "Help on the Way",
    name_pearljam: "Jeremy",
    name_radiohead: "I Might Be Wrong",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "86",
    name: "Suggested Chicken",
    name_phish: "Ocelot",
    name_taylorswift: "Right Where You Left Me",
    name_gratefuldead: "Me and My Uncle",
    name_pearljam: "Red Mosquito",
    name_radiohead: "Bodysnatchers",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "85",
    name: "Car Fold",
    name_phish: "The Mango Songlist",
    name_taylorswift: "Breathe (feat. Colbie Caillat)",
    name_gratefuldead: "The Eleven",
    name_pearljam: "Evacuation",
    name_radiohead: "Gagging Order",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "84",
    name: "Toothbrush Fight",
    name_phish: "Fluffhead",
    name_taylorswift: "I Forgot That You Existed",
    name_gratefuldead: "Fire on the Mountain",
    name_pearljam: "Dance Of The Clairvoyants",
    name_radiohead: "Sulk",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "83",
    name: "Desk Crack",
    name_phish: "Wilson",
    name_taylorswift: "Seven",
    name_gratefuldead: "Touch of Grey",
    name_pearljam: "Just Breathe",
    name_radiohead: "Just",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "82",
    name: "Current Lamp",
    name_phish: "Limb by Limb",
    name_taylorswift: "Girl At Home",
    name_gratefuldead: "Don't Ease Me In",
    name_pearljam: "W.M.A.",
    name_radiohead: "Molasses",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "81",
    name: "Hospital Society",
    name_phish: "Funky Bitch",
    name_taylorswift: "Eyes Open",
    name_gratefuldead: "Mr Charlie",
    name_pearljam: "Green Disease",
    name_radiohead: "A Punchup at the Wedding",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "80",
    name: "Birthday Crook",
    name_phish: "Twist",
    name_taylorswift: "The Last Great American Dynasty",
    name_gratefuldead: "Dupree's Diamond Blues",
    name_pearljam: "Sirens",
    name_radiohead: "Airbag",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "79",
    name: "NNW",
    name_phish: "When the Circus Comes",
    name_taylorswift: "SuperStar",
    name_gratefuldead: "whats become of the baby",
    name_pearljam: "Big Wave",
    name_radiohead: "Supercollider",
    standard_duration: "100",
    weighting: "100",
  },
  {
    id: "78",
    name: "Degas & Shoal",
    name_phish: "Gotta Jibbo",
    name_taylorswift: "Peace",
    name_gratefuldead: "One More Saturday Night",
    name_pearljam: "Come Back",
    name_radiohead: "Coke Babies",
    standard_duration: "350",
    weighting: "100",
  },
  {
    id: "77",
    name: "Lockdown",
    name_phish: "I Never Needed You This Way",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: null,
    weighting: "100",
  },
  {
    id: "76",
    name: "Hydroplane",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: null,
    weighting: "100",
  },
  {
    id: "75",
    name: "William",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: null,
    weighting: "100",
  },
  {
    id: "74",
    name: "Sunbird Stream",
    name_phish: "Gogli Apparatus",
    name_taylorswift: "Out Of The Woods",
    name_gratefuldead: "Alabama Getaway",
    name_pearljam: "Smile",
    name_radiohead: "Kid A",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "73",
    name: "Grey Clouds",
    name_phish: "Petrichor",
    name_taylorswift: "Mary's Songlist (Oh My My My)",
    name_gratefuldead: "Easy Wind",
    name_pearljam: "Lukin",
    name_radiohead: "Prove Yourself",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "72",
    name: "Swashbuckling Squids",
    name_phish: "Wolfman\u2019s Brother",
    name_taylorswift: "Death By A Thousand Cuts",
    name_gratefuldead: "Weather Report Suite",
    name_pearljam: "Man Of The Hour",
    name_radiohead: "Spectre",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "71",
    name: "Stinky Uncle Steve",
    name_phish: "Timber",
    name_taylorswift: "So It Goes...",
    name_gratefuldead: "St. Steven",
    name_pearljam: "Long Road",
    name_radiohead: "The National Anthem",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "70",
    name: "Roadlife",
    name_phish: "Waiting All Night",
    name_taylorswift: "Stay Stay Stay",
    name_gratefuldead: "One More Saturday Night",
    name_pearljam: "Parachutes",
    name_radiohead: "Faithless the Wonder Boy",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "69",
    name: "Davy Gravy",
    name_phish: "How Many People Are You",
    name_taylorswift: "Long Story Short",
    name_gratefuldead: "Playing in the Band",
    name_pearljam: "Come Back",
    name_radiohead: "How Can You Be Sure?",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "68",
    name: "Apologies Owed",
    name_phish: "555",
    name_taylorswift: "Dear John",
    name_gratefuldead: "If the Shoe Fits",
    name_pearljam: "Get Right",
    name_radiohead: "Feral",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "67",
    name: "Eyes Floating in Cups",
    name_phish: "Carini",
    name_taylorswift: "Paper Rings",
    name_gratefuldead: "Althea",
    name_pearljam: "Black",
    name_radiohead: "No Surprises",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "66",
    name: "Petite Pete",
    name_phish: "Runaway Jim",
    name_taylorswift: "Exile",
    name_gratefuldead: "New Speedway Boogie",
    name_pearljam: "Daughter",
    name_radiohead: "There There",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "65",
    name: "Moonbeams",
    name_phish: "Cavern",
    name_taylorswift: "London Boy",
    name_gratefuldead: "Dark Star",
    name_pearljam: "State of Love and Trust",
    name_radiohead: "True Love Waits",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "64",
    name: "Rocketships",
    name_phish: "Rise/Come Together",
    name_taylorswift: "It's Nice To Have A Friend",
    name_gratefuldead: "The Other One",
    name_pearljam: "Release",
    name_radiohead: "Kinetic",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "63",
    name: "Fuzzy Fuzzbuzz",
    name_phish: "Everything\u2019s Right",
    name_taylorswift: "Back to December",
    name_gratefuldead: "Throwing Stones",
    name_pearljam: "Sad",
    name_radiohead: "Packt Like Sardines in a Crushd Tin Box",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "62",
    name: "Self-absorbed Husbands",
    name_phish: "Split Open and Melt",
    name_taylorswift: "Fearless",
    name_gratefuldead: "He's Gone",
    name_pearljam: "Why Go",
    name_radiohead: "Idioteque",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "61",
    name: "Untitled 3",
    name_phish: "Suzy Greenberg",
    name_taylorswift: "Begin Again",
    name_gratefuldead: "Good Lovin",
    name_pearljam: "No Way",
    name_radiohead: "Where Bluebirds Fly",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "60",
    name: "Untitled 2",
    name_phish: "No Man In No Man\u2019s Land",
    name_taylorswift: "Come Back... Be Here",
    name_gratefuldead: "Cold Rain & Snow",
    name_pearljam: "I Am Mine",
    name_radiohead: "Knives Out",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "59",
    name: "Untitled 1",
    name_phish: "Bouncing Around the Room",
    name_taylorswift: "The Best Day",
    name_gratefuldead: "Sugar Magnolia",
    name_pearljam: "Porch",
    name_radiohead: "Pyramid Songlist",
    standard_duration: "300",
    weighting: "100",
  },
  {
    id: "58",
    name: "Mountains of the M",
    name_phish: "no body",
    name_taylorswift: " no crime (feat. HAIM)",
    name_gratefuldead: "Sand",
    name_pearljam: "Thin Air",
    name_radiohead: "How to Disappear Completely",
    standard_duration: "172",
    weighting: "100",
  },
  {
    id: "57",
    name: "Moana",
    name_phish: "Say It To Me S.A.N.T.O.S.",
    name_taylorswift: "Happiness",
    name_gratefuldead: "Mexicali Blues",
    name_pearljam: "I Got ID",
    name_radiohead: "Bullet Proof \u2026 I Wish I Was",
    standard_duration: "403",
    weighting: "100",
  },
  {
    id: "56",
    name: "Bird's Eye",
    name_phish: "Tube",
    name_taylorswift: "Style",
    name_gratefuldead: "Row Jimmy",
    name_pearljam: "Superblood Wolfmoon",
    name_radiohead: "Morning Bell",
    standard_duration: "333",
    weighting: "100",
  },
  {
    id: "55",
    name: "Lavender",
    name_phish: "Wingsuit",
    name_taylorswift: "Welcome to New York",
    name_gratefuldead: "Here Comes Sunshine",
    name_pearljam: "Indifference",
    name_radiohead: "Sit Down. Stand Up.",
    standard_duration: "383",
    weighting: "100",
  },
  {
    id: "54",
    name: "Cochemeleon",
    name_phish: "Bug",
    name_taylorswift: "Fifteen",
    name_gratefuldead: "Lost Sailor",
    name_pearljam: "1/2",
    name_radiohead: "Stupid Car",
    standard_duration: "281",
    weighting: "100",
  },
  {
    id: "53",
    name: "Ananas comosus",
    name_phish: "Bathtub Gin",
    name_taylorswift: "Betty",
    name_gratefuldead: "Eyes",
    name_pearljam: "Once",
    name_radiohead: "Lucky",
    standard_duration: "528",
    weighting: "100",
  },
  {
    id: "52",
    name: "Biker",
    name_phish: "Julius",
    name_taylorswift: "Shake It off",
    name_gratefuldead: "Franklin's Tower",
    name_pearljam: "Better Man",
    name_radiohead: "Harry Patch (In Memory Of)",
    standard_duration: "223",
    weighting: "100",
  },
  {
    id: "51",
    name: "The Big Green Hill",
    name_phish: "More",
    name_taylorswift: "Cardigan",
    name_gratefuldead: "Black Muddy River",
    name_pearljam: "Severed Hand",
    name_radiohead: "Burn the Witch",
    standard_duration: "299",
    weighting: "100",
  },
  {
    id: "50",
    name: "Kofi",
    name_phish: "Dogs",
    name_taylorswift: "This Love",
    name_gratefuldead: "Beat It On Down the Line",
    name_pearljam: "Deep",
    name_radiohead: "You",
    standard_duration: "303",
    weighting: "100",
  },
  {
    id: "49",
    name: "Haleakal\u0101",
    name_phish: "Roggae",
    name_taylorswift: "White Horse",
    name_gratefuldead: "Stagger Lee",
    name_pearljam: "Quick Escape",
    name_radiohead: "The Gloaming",
    standard_duration: "203",
    weighting: "100",
  },
  {
    id: "48",
    name: "Smart Flower",
    name_phish: "Billy Breathes",
    name_taylorswift: "Afterglow",
    name_gratefuldead: "The Golden Road",
    name_pearljam: "Last Kiss",
    name_radiohead: "Life in a Glasshouse",
    standard_duration: "341",
    weighting: "100",
  },
  {
    id: "47",
    name: "Dragonfire",
    name_phish: "Esther",
    name_taylorswift: "The Last Time",
    name_gratefuldead: "Hard to Handle",
    name_pearljam: "Habit",
    name_radiohead: "Inside My Head",
    standard_duration: "450",
    weighting: "100",
  },
  {
    id: "46",
    name: "Spiraling Excitement",
    name_phish: "The Line",
    name_taylorswift: "Bad Blood",
    name_gratefuldead: "Easy Answers",
    name_pearljam: "Bu$hleager",
    name_radiohead: "MK 2",
    standard_duration: "290",
    weighting: "100",
  },
  {
    id: "45",
    name: "Mock Orange Blossom",
    name_phish: "Breath and Burning",
    name_taylorswift: "Crazier",
    name_gratefuldead: "West LA Fadeway",
    name_pearljam: "Love Boat Captain",
    name_radiohead: "Blow Out",
    standard_duration: "730",
    weighting: "100",
  },
  {
    id: "44",
    name: "K\u014dkako",
    name_phish: "What\u2019s the Use",
    name_taylorswift: "22",
    name_gratefuldead: "Deal",
    name_pearljam: "Yellow Ledbetter",
    name_radiohead: "Give Up the Ghost",
    standard_duration: "565",
    weighting: "100",
  },
  {
    id: "43",
    name: "Kiwi Kea",
    name_phish: "Prince Caspian",
    name_taylorswift: "This is why we can't have nice things",
    name_gratefuldead: "Cumberland Blues",
    name_pearljam: "Oceans (remix)",
    name_radiohead: "Let Down",
    standard_duration: "305",
    weighting: "100",
  },
  {
    id: "42",
    name: "Doge Meme",
    name_phish: "Camel Walk",
    name_taylorswift: "Hoax",
    name_gratefuldead: "I Need a Miracle",
    name_pearljam: "Johnny Guitar",
    name_radiohead: "Lurgee",
    standard_duration: "180",
    weighting: "100",
  },
  {
    id: "41",
    name: "Opalescence ",
    name_phish: "Lawn Boy",
    name_taylorswift: "Illicit Affairs",
    name_gratefuldead: "Hell in a Bucket",
    name_pearljam: "Satan\u2019s Bed",
    name_radiohead: "Worrywort",
    standard_duration: "410",
    weighting: "100",
  },
  {
    id: "40",
    name: "Deer Crash",
    name_phish: "Soul Planet",
    name_taylorswift: "Ivy",
    name_gratefuldead: "U.S. Blues",
    name_pearljam: "Spin The Black Circle",
    name_radiohead: "Planet Telex",
    standard_duration: "220",
    weighting: "100",
  },
  {
    id: "39",
    name: "Shh I'm Thinking",
    name_phish: "Fuego",
    name_taylorswift: "Stay beautiful",
    name_gratefuldead: "Loose Lucy",
    name_pearljam: "Down",
    name_radiohead: "Lull",
    standard_duration: "200",
    weighting: "100",
  },
  {
    id: "38",
    name: "Cranberry Crystals",
    name_phish: "Maze",
    name_taylorswift: "Lover",
    name_gratefuldead: "Crazy Fingers",
    name_pearljam: "Wishlist",
    name_radiohead: "Lotus Flower",
    standard_duration: "190",
    weighting: "100",
  },
  {
    id: "37",
    name: "Greypeak Range",
    name_phish: "AC/DC Bag",
    name_taylorswift: "All Too Well",
    name_gratefuldead: "Morning Dew",
    name_pearljam: "Long Road",
    name_radiohead: "Daydreaming",
    standard_duration: "202",
    weighting: "100",
  },
  {
    id: "36",
    name: "The Turning Machine",
    name_phish: "Miss You",
    name_taylorswift: "Mean",
    name_gratefuldead: "Viola Lee Blues",
    name_pearljam: "Buckle Up",
    name_radiohead: "Banana Co.",
    standard_duration: "282",
    weighting: "100",
  },
  {
    id: "35",
    name: "The Wax Post",
    name_phish: "First Tube",
    name_taylorswift: "...Ready For It?",
    name_gratefuldead: "Unbroken Chain",
    name_pearljam: "Footsteps",
    name_radiohead: "Weird Fishes/Arpeggi",
    standard_duration: "192",
    weighting: "100",
  },
  {
    id: "34",
    name: "Raiya Sees",
    name_phish: "Slave to the Traffic Light",
    name_taylorswift: "August",
    name_gratefuldead: "Uncle John's Band",
    name_pearljam: "Given To Fly",
    name_radiohead: "Reckoner",
    standard_duration: "212",
    weighting: "100",
  },
  {
    id: "33",
    name: "Duke's Journey",
    name_phish: "Soul Shakedown Party",
    name_taylorswift: "Look What You Made Me Do",
    name_gratefuldead: "Saint of Circumstance",
    name_pearljam: "Glorified G",
    name_radiohead: "Vegetable",
    standard_duration: "532",
    weighting: "100",
  },
  {
    id: "32",
    name: "Spiron Festival",
    name_phish: "Possum",
    name_taylorswift: "Tolerate It",
    name_gratefuldead: "Box of Rain",
    name_pearljam: "Crazy Mary",
    name_radiohead: "Exit Music (For a Film)",
    standard_duration: "249",
    weighting: "100",
  },
  {
    id: "31",
    name: "Ku-Tut",
    name_phish: "Alumni Blues",
    name_taylorswift: "False God",
    name_gratefuldead: "Day Job",
    name_pearljam: "Low Light",
    name_radiohead: "Million Dollar Question",
    standard_duration: "409",
    weighting: "100",
  },
  {
    id: "30",
    name: "Olivia's Pots",
    name_phish: "Mike\u2019s Songlist",
    name_taylorswift: "Dress",
    name_gratefuldead: "Goin Down the Road Feeling Bad",
    name_pearljam: "Garden",
    name_radiohead: "2 + 2 = 5",
    standard_duration: "252",
    weighting: "100",
  },
  {
    id: "29",
    name: "Moonstrike's Lament",
    name_phish: "Haley\u2019s Comet",
    name_taylorswift: "The Man",
    name_gratefuldead: "China Cat Sunflower",
    name_pearljam: "Animal",
    name_radiohead: "Everything in Its Right Place",
    standard_duration: "302",
    weighting: "100",
  },
  {
    id: "28",
    name: "Krambambuli",
    name_phish: "Tweezer",
    name_taylorswift: "Long live",
    name_gratefuldead: "The other one",
    name_pearljam: "Not For You",
    name_radiohead: "Fake Plastic Trees",
    standard_duration: "70",
    weighting: "100",
  },
  {
    id: "27",
    name: "Our 27th Songlist",
    name_phish: "Reba",
    name_taylorswift: "Style",
    name_gratefuldead: "Broke Down Palace",
    name_pearljam: "Nothing As It Seems",
    name_radiohead: "Climbing Up the Walls",
    standard_duration: "211",
    weighting: "100",
  },
  {
    id: "26",
    name: "A9",
    name_phish: "Kill Devil Falls",
    name_taylorswift: "Cowboy Like Me",
    name_gratefuldead: "Dire Wolf",
    name_pearljam: "Amongst The Waves",
    name_radiohead: "All I Need",
    standard_duration: "340",
    weighting: "100",
  },
  {
    id: "25",
    name: "Another Brick in the Wall",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: "389",
    weighting: "0",
  },
  {
    id: "24",
    name: "Don't Let the Air Out of My Tires",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: "291",
    weighting: "0",
  },
  {
    id: "23",
    name: "What a Wonderful World",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: "283",
    weighting: "0",
  },
  {
    id: "22",
    name: "Little Bones",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: "270",
    weighting: "0",
  },
  {
    id: "21",
    name: "Celsius",
    name_phish: "Moma Dance",
    name_taylorswift: "Tis The Damn Season",
    name_gratefuldead: "Til the Morning Comes",
    name_pearljam: "The Fixer",
    name_radiohead: "Videotape",
    standard_duration: "400",
    weighting: "100",
  },
  {
    id: "20",
    name: "Guyute",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: "530",
    weighting: "0",
  },
  {
    id: "19",
    name: "Midst",
    name_phish: "Down with Disease",
    name_taylorswift: "Delicate",
    name_gratefuldead: "Scarlet Begonias",
    name_pearljam: "Pendulum",
    name_radiohead: "Subterranean Homesick Alien",
    standard_duration: "214",
    weighting: "100",
  },
  {
    id: "18",
    name: "F-12",
    name_phish: "Character Zero",
    name_taylorswift: "Miss Americana & The Heartbreak Prince",
    name_gratefuldead: "It Must Have Been the Roses",
    name_pearljam: "Do The Evolution",
    name_radiohead: "Like Spinning Plates",
    standard_duration: "60",
    weighting: "100",
  },
  {
    id: "17",
    name: "High School",
    name_phish: "Chalk Dust Torture",
    name_taylorswift: "Hail",
    name_gratefuldead: "Love Story",
    name_pearljam: " Hail",
    name_radiohead: "Street Spirit (Fade Out)",
    standard_duration: "202",
    weighting: "100",
  },
  {
    id: "16",
    name: "Patrick Swayze",
    name_phish: "Punch You In the Eye",
    name_taylorswift: "Champagne Problems",
    name_gratefuldead: "Friend of the Devil",
    name_pearljam: "Rats",
    name_radiohead: "The Tourist",
    standard_duration: "178",
    weighting: "100",
  },
  {
    id: "15",
    name: "Needle",
    name_phish: "Ass Handed",
    name_taylorswift: "You Need to Calm Down",
    name_gratefuldead: "France",
    name_pearljam: "Bugs",
    name_radiohead: "Pop Is Dead",
    standard_duration: "375",
    weighting: "100",
  },
  {
    id: "14",
    name: "Wave to the Wind",
    name_phish: "Saw It Again",
    name_taylorswift: "Push Me",
    name_gratefuldead: "ME!",
    name_pearljam: " Pull Me",
    name_radiohead: "Nothing Touches Me",
    standard_duration: "180",
    weighting: "100",
  },
  {
    id: "13",
    name: "Pixilxil",
    name_phish: "x",
    name_taylorswift: "x",
    name_gratefuldead: "x",
    name_pearljam: "x",
    name_radiohead: "x",
    standard_duration: "200",
    weighting: "0",
  },
  {
    id: "12",
    name: "Waiting for Fred",
    name_phish: "Your Pet Cat",
    name_taylorswift: "We Are Never Ever Getting Back Together",
    name_gratefuldead: "Days Between",
    name_pearljam: "Thin Air",
    name_radiohead: "Thinking About You",
    standard_duration: "602",
    weighting: "100",
  },
  {
    id: "11",
    name: "Blue Orange",
    name_phish: "Harry Hood",
    name_taylorswift: "Blank Space",
    name_gratefuldead: "Truckin",
    name_pearljam: "Rearviewmirror",
    name_radiohead: "Creep",
    standard_duration: "273",
    weighting: "100",
  },
  {
    id: "10",
    name: "On the Low Rung",
    name_phish: "The Birds",
    name_taylorswift: "New Year's Day",
    name_gratefuldead: "All New Minglewood Blues",
    name_pearljam: "Soon Forget",
    name_radiohead: "I Am Citizen Insane",
    standard_duration: "230",
    weighting: "100",
  },
  {
    id: "9",
    name: "Top",
    name_phish: "Big Black Furry Creature from Mars",
    name_taylorswift: "Picture to burn",
    name_gratefuldead: "Jack Straw",
    name_pearljam: "Sonic Reducer",
    name_radiohead: "15 Step",
    standard_duration: "401",
    weighting: "100",
  },
  {
    id: "8",
    name: "Duke's Revenge",
    name_phish: "Mercury",
    name_taylorswift: "Call It What You Want",
    name_gratefuldead: "The Music Never Stopped",
    name_pearljam: "Wash",
    name_radiohead: "Nude",
    standard_duration: "342",
    weighting: "100",
  },
  {
    id: "7",
    name: "Four Turtles",
    name_phish: "Contact",
    name_taylorswift: "I Knew You Were Trouble",
    name_gratefuldead: "Not Fade Away",
    name_pearljam: "Thumbing My Way",
    name_radiohead: "Where I End and You Begin",
    standard_duration: "302",
    weighting: "100",
  },
  {
    id: "6",
    name: "Sure",
    name_phish: "Theme From the Bottom",
    name_taylorswift: "False God",
    name_gratefuldead: "Greatest Story Ever Told",
    name_pearljam: "Present Tense",
    name_radiohead: "Talk Show Host",
    standard_duration: "196",
    weighting: "100",
  },
  {
    id: "5",
    name: "Reload",
    name_phish: "The Divided Sky",
    name_taylorswift: "You Belong With Me",
    name_gratefuldead: "Ripple",
    name_pearljam: "Corduroy",
    name_radiohead: "Paranoid Android",
    standard_duration: "350",
    weighting: "100",
  },
  {
    id: "4",
    name: "The First Show",
    name_phish: "Contact",
    name_taylorswift: "Cruel Summer",
    name_gratefuldead: "Turn on Your Lovelight",
    name_pearljam: "Elderly Woman Behind The Counter In A Small Town",
    name_radiohead: "Glass Eyes",
    standard_duration: "500",
    weighting: "100",
  },
  {
    id: "3",
    name: "Ticket",
    name_phish: "David Bowie",
    name_taylorswift: "Sparks Fly",
    name_gratefuldead: "Casey Jones",
    name_pearljam: "Even Flow",
    name_radiohead: "Karma Police",
    standard_duration: "437",
    weighting: "100",
  },
  {
    id: "2",
    name: "Blended Together",
    name_phish: "Sanity",
    name_taylorswift: "Willow",
    name_gratefuldead: "Corrina",
    name_pearljam: "Pilate",
    name_radiohead: "How Do You?",
    standard_duration: "205",
    weighting: "100",
  },
  {
    id: "1",
    name: "The Wave",
    name_phish: "Farmhouse",
    name_taylorswift: "Mine",
    name_gratefuldead: "Money Money",
    name_pearljam: "Around the Bend",
    name_radiohead: "I Am a Wicked Child",
    standard_duration: "250",
    weighting: "100",
  },
];
export function getSonglists() {
  return Songlists;
}

export function getSonglist(id) {
  return Songlists.find((Songlist) => Songlist.id === id);
}
